### ISSUE TITLE
quits if the task takes more than 15min

### ISSUE THREAD

**Issue by Necmttn** [feross/run-series#12]
if I put small tasks which take seconds for finish it works fine.
![image](https://user-images.githubusercontent.com/5212808/28967726-153cdc3e-794f-11e7-961c-1d2d5646efc2.png)

with the same setup.
if I put tasks which take ~10-15min
it doesn't run the second task.
![image](https://user-images.githubusercontent.com/5212808/28967617-99b39620-794e-11e7-9277-e941f9369c5e.png)

![image](https://user-images.githubusercontent.com/5212808/28967610-90e7b684-794e-11e7-85a0-ea844d3107e4.png)
it's quits after the first task completed.

**Comment by feross** [comment]
Thanks for the issue! This is almost certainly a bug in your own code. If you have a minimal code example that can demonstrate an actually issue here, then please post it here!
