### ISSUE TITLE
Allow tasks to be object

### ISSUE THREAD

**Issue by emilbayes** [feross/run-series#4]
Allow the following:

```js
series({
   task1: function(next) { ... },
   task2: function(next) { ... },
   ...
}, function(err, results) {
   console.log(results.task1);
});
```

I'd love to do a PR if interested :)

**Comment by feross** [comment]
The problem with this is that keys in an object are not ordered, except by
accident (as an implementation detail) in V8. The keys are not guaranteed
to be ordered in other JS environments, so then what order would the
functions get executed in?

**Comment by emilbayes** [comment]
You are right, didn't think about that! I guess this won't be possible before ES6 Maps come into common use.

**Comment by dcousens** [comment]
I dropped this into an application recently,  and didn't realise the tasks object didn't work,  here I was ready to be like "Feross!", and then I read the above, and now I'm smiling.

@feross saving me from my own mistakes once again...
Could be worth a README note though. Haha.

**Comment by feross** [comment]
@dcousens Hahaha, glad I could be a help :)
